version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Authenticate
          command: . build/setup-dev06.sh
      - run:
          name: Validate Components & Run Tests
          command: . build/test-dev06.sh
      - store_test_results:
          path: test-results
workflows:
  version: 2
  validate:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - Target2
              ignore:
                - Source
                - master
                - PROD
                - Target
                - Source2
